services:
  lgtm:
    image: grafana/otel-lgtm:latest
    container_name: lgtm
    ports:
      - "3000:3000"   # Grafana UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - OTEL_SERVICE_NAME=myapp-backend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
    depends_on:
      - lgtm
