package tech.kingoyster.spring_1.model;
// Generated Oct 3, 2025, 1:25:21 PM by Hibernate Tools 7.1.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name="customers"
)
public class Customers  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private Timestamp registeredAt;

    public Customers() {
    }

	
    public Customers(int id, String name, String email) {
        this.id = id;
        this.name = name;
        this.email = email;
    }
    public Customers(int id, String name, String email, Timestamp registeredAt) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.registeredAt = registeredAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", nullable=false, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registered_at", length=19)
    public Timestamp getRegisteredAt() {
        return this.registeredAt;
    }
    
    public void setRegisteredAt(Timestamp registeredAt) {
        this.registeredAt = registeredAt;
    }




}


