server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: myapp-backend
  data:
    redis:
      host: ${VALKEY_HOST:localhost}
      port: ${VALKEY_PORT:6379}
  docker:
    compose:
      enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
