# apiVersion: apps/v1
# kind: Deployment
apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: lab
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
      env:
        - name: MODE
          value: "demo"